defmodule HexHubWeb.Endpoint do
  use Phoenix.Endpoint, otp_app: :hex_hub

  # The session will be stored in the cookie and signed,
  # this means its contents can be read but not tampered with.
  # Set :encryption_salt if you would also like to encrypt it.
  @session_options [
    store: :cookie,
    key: "_hex_hub_",
    signing_salt: "tHS+SonG",
    same_site: "Lax"
  ]

  socket "/live", Phoenix.LiveView.Socket,
    websocket: [connect_info: [session: @session_options]],
    longpoll: [connect_info: [session: @session_options]]

  # Serve at "/" the static files from "priv/static" directory.
  #
  # When code reloading is disabled (e.g., in production),
  # the `gzip` option is enabled to serve compressed
  # static files generated by running `phx.digest`.
  plug Plug.Static,
    at: "/",
    from: :hex_hub,
    gzip: not code_reloading?,
    only: HexHubWeb.static_paths()

  # Code reloading can be explicitly enabled under the
  # :code_reloader configuration of your endpoint.
  if code_reloading? do
    socket "/phoenix/live_reload/socket", Phoenix.LiveReloader.Socket
    plug Phoenix.LiveReloader
    plug Phoenix.CodeReloader
  end

  plug Phoenix.LiveDashboard.RequestLogger,
    param_key: "request_logger",
    cookie_key: "request_logger"

  # Trust reverse proxy headers (x-forwarded-for, x-forwarded-proto, x-forwarded-port)
  plug Plug.RewriteOn, [
    :x_forwarded_for,
    :x_forwarded_host,
    :x_forwarded_port,
    :x_forwarded_proto
  ]

  plug Plug.RequestId
  plug Plug.Telemetry, event_prefix: [:phoenix, :endpoint]

  # Handle Expect: 100-continue header before reading body
  # This is required for hex client package publishing
  plug HexHubWeb.Plugs.ExpectContinue

  plug Plug.Parsers,
    parsers: [:urlencoded, :multipart, :json, HexHubWeb.Parsers.TarballParser],
    pass: ["*/*"],
    json_decoder: Phoenix.json_library(),
    length: 100_000_000

  plug Plug.MethodOverride
  plug Plug.Head
  plug Plug.Session, @session_options
  plug HexHubWeb.Router
end
